function getSwipePerView() { return window.innerWidth >= 1024 ? 4 : window.innerWidth >= 640 ? 3 : 2; }
function swipeGo(id, idx) { const track = document.getElementById(`track-${id}`), wrap = document.getElementById(`wrap-${id}`); if (!track || !wrap) return; const cards = track.querySelectorAll('.product-card'); if (!cards.length) return; const perView = getSwipePerView(); idx = Math.max(0, Math.min(idx, Math.max(0, cards.length - perView))); S.swipeState[id] = idx; track.style.transform = `translateX(-${idx * (wrap.offsetWidth / perView + 8)}px)`; document.querySelectorAll(`#bars-${id} .swipe-bar`).forEach((b,i)=>b.classList.toggle('active',i===idx)); }
function goSwipe(id, idx) { swipeGo(id, idx); }
function swipeTouchStart(e, id) { S.swipeState[`${id}_startX`] = e.touches[0].clientX; }
function swipeTouchEnd(e, id) { const startX = S.swipeState[`${id}_startX`]; if (startX === undefined) return; const diff = startX - e.changedTouches[0].clientX; if (Math.abs(diff) < 30) return; const cur = S.swipeState[id] || 0; if (diff > 0) swipeGo(id, cur + 1); else swipeGo(id, cur - 1); }
function swipeMouseDown(e, id) { S.swipeState[`${id}_mouseX`] = e.clientX; S.swipeState[`${id}_dragging`] = true; const onUp = (ev) => { if (!S.swipeState[`${id}_dragging`]) return; S.swipeState[`${id}_dragging`] = false; const diff = S.swipeState[`${id}_mouseX`] - ev.clientX; if (Math.abs(diff) < 20) { document.removeEventListener('mouseup', onUp); return; } const cur = S.swipeState[id] || 0; if (diff > 0) swipeGo(id, cur + 1); else swipeGo(id, cur - 1); document.removeEventListener('mouseup', onUp); }; document.addEventListener('mouseup', onUp); }
function refreshSwipeTracks() { document.querySelectorAll('.swipe-track-wrap').forEach(wrap => { const id = wrap.id.replace('wrap-', ''); const track = document.getElementById(`track-${id}`); if (track) track.style.transform = 'translateX(0)'; document.getElementById(`bars-${id}`)?.querySelectorAll('.swipe-bar').forEach((b,i)=>b.classList.toggle('active',i===0)); S.swipeState[id] = 0; }); }
function buildCampaignSlider(){if(!DOM.campaignSlides)return;const prods=merchandiseProducts(PRODUCTS.filter(p=>p.status==='active'));const pages=Math.ceil(prods.length/4);DOM.campaignSlides.innerHTML=Array.from({length:pages},(_,i)=>`<div class="campaign-slide">${prods.slice(i*4,(i+1)*4).map(p=>productCard(p)).join("")}</div>`).join("");}
function moveCampaignSlider(dir){const total=Math.ceil(PRODUCTS.filter(p=>p.status==='active').length/4)||1;S.campaignSlideIndex=(S.campaignSlideIndex+dir+total)%total;if(DOM.campaignSlides)DOM.campaignSlides.style.transform=`translateX(-${S.campaignSlideIndex*100}%)`;}
